name = "PhyloPlot"
uuid = "e9e37ff7-8a32-4606-8abd-1017db40dd22"
authors = ["Akitoro"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
